Fix concourse set-pipeline error
Started seeing this error recently, perhaps due to a recent upgrade?

```
$ fly --target ga set-pipeline --pipeline routing --config pipelines/routing.yml
error: error unmarshaling JSON: while decoding JSON: malformed task step: json: cannot unmarshal number into Go struct field TaskRunConfig.config.run.args of type string
```